### ISSUE TITLE
ImportError: No module named netaddr

### ISSUE THREAD

**Issue by esohbx** [deep-security/amazon-inspector#1]
Thanks for taking the time to submit an issue. There's a couple of things that will make this easier for everyone involve. If you could please take the time to complete the list below, it's much appreciated.

- [ ] I'm using Deep Security version ____

- [x ] I'm using the latest version of this repo

- [ ] My Deep Security Manager has a self-signed or non-validating SSL certificate

## Current Output

Please re-run the command using ```--verbose``` and provide the complete output below.

## Addition Details
Runing python ds-analyze-findings.py help 
results in missing module
Can you also please fill in each of the remaining sections.
### Expected behaviour 
python ds-analyze-findings.py help
see help as described in README
### Actual behaviour 
python ds-analyze-findings.py help
Traceback (most recent call last):
 File "ds-analyze-findings.py", line 12, in <module>
 import netaddr
ImportError: No module named netaddr

### Steps to reproduce the behaviour
Cloned the repo
cd amazon-inspector
python ds-analyze-findings.py --verbose
Traceback (most recent call last):
  File "ds-analyze-findings.py", line 12, in <module>
    import netaddr
ImportError: No module named netaddr

Thanks for your help.

**Comment by marknca** [comment]
Apologies on the delayed response, I've been having some issues with notifications. The requirement isn't actually needed so I've removed the import statement wth commit https://github.com/deep-security/amazon-inspector/commit/847723e7f47e685f46cf4027b5fa01835eb60bc3
